%% ===============================
%% Developer - Project - Tech Model Diagram
%% ===============================

classDiagram
    class Developer {
        +int id
        +string name
        +string badge
        +string subtitle
        +string title
        +string bio
        +string description
        +string image
        +string linkedin
        +string github
    }

    class Project {
        +int id
        +string title
        +string description
        +string image
        +string github_link
        +string demo_link
    }

    %% Relationships
    Developer "1" --> "*" Project : owns
