graph TD
    subgraph Home["Home Page"]
        A1[Profile]
        A2[About]
    end

    subgraph ProjectsPage["Projects Page"]
        B[Projects List]
        D[Project Details]
    end


    A1 --> B   
    A2 --> B    
    B --> D     
    D --> B 

    %% Styling
    classDef main fill:#fffbe6,stroke:#000,color:#000,stroke-width:1px;
    classDef node fill:#f9f9ff,stroke:#666,color:#000,stroke-width:1px;

    class Home,ProjectsPage main;
    class A1,A2,B,D node;
